// ─── AI Automation Types ───
type AITaskPhase = 'BACKLOG' | 'DONE' | string
type AIGitStrategy = 'worktree' | 'none'

type AIPipelineRole = 'worker' | 'planner' | 'reviewer' | 'git'

interface AIPipelinePhase {
  id: string
  name: string
  type: 'agent' | 'manual'
  prompt?: string
  roles?: AIPipelineRole[]
  customTools?: string
  /** @deprecated Use roles + customTools instead */
  allowedTools?: string
  rejectPattern?: string
  rejectTarget?: string
  color?: string
  stallTimeout?: number
}

interface AITaskProject {
  path: string
  label: string
  gitStrategy: AIGitStrategy
  baseBranch?: string
  customBranchName?: string
}

interface AIProjectDiff {
  project: string  // project label
  path: string     // project path
  diff: string     // raw git diff
}

interface AITask {
  id: string
  title: string
  description: string
  boardId: string
  phase: AITaskPhase
  createdAt: string
  updatedAt: string
  projects: AITaskProject[]
  worktrees: AITaskWorktree[]
  plan?: string               // Deprecated — use task directory files
  taskDirPath?: string
  reviewComments?: AIReviewComment[]
  humanComments?: AIHumanComment[]
  activeProcessPid?: number
  currentPhaseName?: string
  needsUserInput: boolean
  needsUserInputReason?: AITaskAttentionReason
  stallRetryCount?: number
  phaseHistory: AIPhaseHistoryEntry[]
  excludedFiles?: string[]
  amendments?: AITaskAmendment[]
  linkedTaskIds?: string[]
  /** @deprecated Use projects[].gitStrategy instead */
  gitStrategy?: AIGitStrategy
  /** @deprecated Use projects[].baseBranch instead */
  baseBranch?: string
  /** @deprecated Use projects[].customBranchName instead */
  customBranchName?: string
  /** @deprecated Use projects[].path instead */
  branchName?: string
  /** @deprecated Use projects instead */
  projectPaths?: string[]
}

type AIPhaseHistoryEvent = 'completed' | 'stopped' | 'crashed' | 'stalled' | 'error'

interface AIPhaseHistoryEntry {
  phase: string
  enteredAt: string
  exitedAt?: string
  exitEvent?: AIPhaseHistoryEvent
  contextHistoryPath?: string
}

interface AITaskWorktree {
  projectPath: string
  worktreePath: string
  branchName: string
}

interface AIReviewComment {
  file: string
  line?: number
  comment: string
  severity: 'critical' | 'suggestion' | 'nitpick'
}

interface AIBoard {
  id: string
  name: string
  color: string
  pipeline: AIPipelinePhase[]
  createdAt: string
}

type AITaskAttentionReason = 'crashed' | 'stalled' | 'max_retries' | 'error'

interface AINotification {
  id: string
  taskId: string
  taskTitle: string
  type: 'manual_phase' | 'needs_attention' | 'task_done' | 'phase_start'
  message: string
  createdAt: string
  read: boolean
}

interface AIHumanComment {
  id: string
  file: string
  line: number
  comment: string
  createdAt: string
  resolved?: boolean
  resolvedBy?: ('human' | 'agent')[]
}

interface AITaskAmendment {
  id: string
  text: string
  targetPhase: string
  createdAt: string
  hidden?: boolean
}

interface AIBranchCommit {
  hash: string
  shortHash: string
  message: string
}

interface AIBranchInfo {
  worktreePath: string
  projectPath: string
  projectLabel: string
  branchName: string
  hasRemote: boolean
  prNumber: number | null
  prUrl: string | null
  commits: AIBranchCommit[]
}

interface AIKnowledgeDoc {
  id: string
  title: string
  content: string
  sourcePath?: string
  generatingStatus?: string
  createdAt: string
  updatedAt: string
  autoGenerated: boolean
}

interface AIAutomationSettings {
  maxConcurrency: number
  boards: AIBoard[]
  activeBoardId: string
  defaultGitStrategy: AIGitStrategy
  defaultBaseBranch: string
  taskDataRoot?: string
  phasePrompts: {
    planning: string
    working: string
    reviewing: string
  }
  globalRules: string
  knowledgeDocs: AIKnowledgeDoc[]
  stallTimeoutMinutes: number
  notifyOnManualPhase: boolean
  notifyOnNeedsAttention: boolean
  notifyOnTaskDone: boolean
  notifyOnPhaseStart: boolean
  // UI preferences
  theme?: 'dark' | 'light'
  diffViewMode?: 'unified' | 'split'
  showResolvedComments?: boolean
  defaultRequestChangesPhase?: string
  defaultAmendmentPhase?: string
  defaultApprovePhase?: string
  approveSkipConfirm?: boolean
  fileViewMode?: 'list' | 'grid' | 'tree'
  visibleViews?: string[]
}

interface AITaskOutput {
  taskId: string
  output: string
}

interface AIAgentStats {
  taskId: string
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
  contextWindowMax: number
  peakContext: number
  turns: number
  toolCalls: number
  toolNames: string[]
  costUsd: number
  startedAt: string
}
