/* eslint-disable @typescript-eslint/triple-slash-reference */
/// <reference path="services.d.ts" />
/// <reference path="queues.d.ts" />
/// <reference path="workflows.d.ts" />
/// <reference path="app.d.ts" />
/// <reference path="api-client.d.ts" />
/// <reference path="docker.d.ts" />
/// <reference path="mongodb.d.ts" />
/// <reference path="ai-automation.d.ts" />
/// <reference path="sql.d.ts" />
/// <reference path="dynamodb.d.ts" />
/// <reference path="brokers.d.ts" />
/// <reference path="planner.d.ts" />
/// <reference path="project-knowledge.d.ts" />
/// <reference path="ipc.d.ts" />
