import { useState, type FC } from 'react'
import { useAIAutomation } from '@/ui/contexts/ai-automation'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { ArrowLeft, Plus, Trash2 } from 'lucide-react'

interface AISettingsProps {
  onBack: () => void
}

export const AISettings: FC<AISettingsProps> = ({ onBack }) => {
  const { settings, updateSettings } = useAIAutomation()

  if (!settings) return <div className="h-full flex items-center justify-center text-neutral-500">Loading settings...</div>

  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center gap-3 px-4 py-3 border-b border-neutral-700">
        <Button variant="ghost" size="sm" onClick={onBack}>
          <ArrowLeft className="h-4 w-4" />
        </Button>
        <h2 className="text-lg font-semibold text-white">AI Automation Settings</h2>
      </div>

      <Tabs defaultValue="knowledge" className="flex-1 flex flex-col min-h-0">
        <TabsList className="mx-4 mt-2 w-fit">
          <TabsTrigger value="knowledge">Knowledge Docs</TabsTrigger>
          <TabsTrigger value="prompts">Phase Prompts</TabsTrigger>
          <TabsTrigger value="rules">Global Rules</TabsTrigger>
          <TabsTrigger value="general">General</TabsTrigger>
        </TabsList>

        <TabsContent value="knowledge" className="flex-1 min-h-0 overflow-y-auto px-4 pb-4">
          <KnowledgeDocsTab settings={settings} updateSettings={updateSettings} />
        </TabsContent>

        <TabsContent value="prompts" className="flex-1 min-h-0 overflow-y-auto px-4 pb-4">
          <PhasePromptsTab settings={settings} updateSettings={updateSettings} />
        </TabsContent>

        <TabsContent value="rules" className="flex-1 min-h-0 overflow-y-auto px-4 pb-4">
          <div className="space-y-2 mt-4">
            <Label>Global rules applied to all agents</Label>
            <Textarea
              value={settings.globalRules}
              onChange={e => updateSettings({ globalRules: e.target.value })}
              placeholder="Enter global rules in markdown. These are included in every agent prompt..."
              rows={15}
              className="font-mono text-sm"
            />
          </div>
        </TabsContent>

        <TabsContent value="general" className="flex-1 min-h-0 overflow-y-auto px-4 pb-4">
          <GeneralTab settings={settings} updateSettings={updateSettings} />
        </TabsContent>
      </Tabs>
    </div>
  )
}

// --- Sub-components ---

interface SettingsTabProps {
  settings: AIAutomationSettings
  updateSettings: (updates: Partial<AIAutomationSettings>) => void
}

const KnowledgeDocsTab: FC<SettingsTabProps> = ({ settings, updateSettings }) => {
  const [editingId, setEditingId] = useState<string | null>(null)

  const addDoc = () => {
    const newDoc: AIKnowledgeDoc = {
      id: crypto.randomUUID(),
      title: 'New Document',
      content: '',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      autoGenerated: false
    }
    updateSettings({ knowledgeDocs: [...settings.knowledgeDocs, newDoc] })
    setEditingId(newDoc.id)
  }

  const updateDoc = (id: string, updates: Partial<AIKnowledgeDoc>) => {
    const docs = settings.knowledgeDocs.map(d =>
      d.id === id ? { ...d, ...updates, updatedAt: new Date().toISOString() } : d
    )
    updateSettings({ knowledgeDocs: docs })
  }

  const deleteDoc = (id: string) => {
    updateSettings({ knowledgeDocs: settings.knowledgeDocs.filter(d => d.id !== id) })
    if (editingId === id) setEditingId(null)
  }

  const editingDoc = settings.knowledgeDocs.find(d => d.id === editingId)

  if (editingDoc) {
    return (
      <div className="space-y-3 mt-4">
        <Button variant="ghost" size="sm" onClick={() => setEditingId(null)}>
          <ArrowLeft className="h-4 w-4 mr-1" /> Back to list
        </Button>
        <Input
          value={editingDoc.title}
          onChange={e => updateDoc(editingDoc.id, { title: e.target.value })}
          className="text-lg font-semibold"
        />
        <Textarea
          value={editingDoc.content}
          onChange={e => updateDoc(editingDoc.id, { content: e.target.value })}
          placeholder="Write knowledge in markdown. Describe your system architecture, project relationships, tech stacks..."
          rows={20}
          className="font-mono text-sm"
        />
      </div>
    )
  }

  return (
    <div className="space-y-3 mt-4">
      <div className="flex justify-between items-center">
        <p className="text-sm text-neutral-400">
          Knowledge documents describe your system. Agents use these as context when planning and working.
        </p>
        <Button size="sm" onClick={addDoc}>
          <Plus className="h-4 w-4 mr-1" /> Add Doc
        </Button>
      </div>
      {settings.knowledgeDocs.length === 0 ? (
        <div className="text-neutral-600 text-sm py-8 text-center border border-dashed border-neutral-700 rounded">
          No knowledge docs yet. Add one to help agents understand your projects.
        </div>
      ) : (
        <div className="space-y-2">
          {settings.knowledgeDocs.map(doc => (
            <div key={doc.id} className="flex items-center justify-between p-3 bg-neutral-800 rounded border border-neutral-700 hover:border-neutral-600 transition-colors">
              <div className="cursor-pointer flex-1" onClick={() => setEditingId(doc.id)}>
                <div className="flex items-center gap-2">
                  <p className="text-sm font-medium text-white">{doc.title}</p>
                  {doc.autoGenerated && (
                    <span className="text-[10px] px-1.5 py-0.5 rounded bg-blue-900/50 text-blue-300">auto-generated</span>
                  )}
                </div>
                <p className="text-xs text-neutral-500 mt-0.5">Updated {new Date(doc.updatedAt).toLocaleDateString()}</p>
              </div>
              <Button variant="ghost" size="sm" onClick={(e) => { e.stopPropagation(); deleteDoc(doc.id) }}>
                <Trash2 className="h-4 w-4 text-red-400" />
              </Button>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

const PhasePromptsTab: FC<SettingsTabProps> = ({ settings, updateSettings }) => {
  const updatePhasePrompt = (phase: 'planning' | 'working' | 'reviewing', value: string) => {
    updateSettings({
      phasePrompts: { ...settings.phasePrompts, [phase]: value }
    })
  }

  const phaseDescriptions = {
    planning: 'The planner explores codebases, asks clarifying questions, and produces implementation plans.',
    working: 'The worker implements changes according to the plan, creates commits.',
    reviewing: 'The reviewer checks code changes against the plan and rules, approves or rejects.'
  }

  return (
    <div className="space-y-6 mt-4">
      {(['planning', 'working', 'reviewing'] as const).map(phase => (
        <div key={phase}>
          <Label className="capitalize text-white">{phase} Agent Prompt</Label>
          <p className="text-xs text-neutral-500 mt-0.5 mb-2">{phaseDescriptions[phase]}</p>
          <Textarea
            value={settings.phasePrompts[phase]}
            onChange={e => updatePhasePrompt(phase, e.target.value)}
            placeholder={`Custom system prompt for the ${phase} agent. Leave empty to use the default prompt...`}
            rows={6}
            className="font-mono text-sm"
          />
        </div>
      ))}
    </div>
  )
}

const GeneralTab: FC<SettingsTabProps> = ({ settings, updateSettings }) => {
  return (
    <div className="space-y-4 mt-4 max-w-md">
      <div>
        <Label>Max Concurrent Agents</Label>
        <p className="text-xs text-neutral-500 mb-1">How many tasks can run agents simultaneously.</p>
        <Input
          type="number"
          value={settings.maxConcurrency}
          onChange={e => updateSettings({ maxConcurrency: Math.max(1, Math.min(5, Number(e.target.value))) })}
          min={1}
          max={5}
          className="w-24"
        />
      </div>
      <div>
        <Label>Default Max Review Cycles</Label>
        <p className="text-xs text-neutral-500 mb-1">How many times the reviewer can send work back before escalating to human review.</p>
        <Input
          type="number"
          value={settings.defaultMaxReviewCycles}
          onChange={e => updateSettings({ defaultMaxReviewCycles: Math.max(1, Math.min(10, Number(e.target.value))) })}
          min={1}
          max={10}
          className="w-24"
        />
      </div>
      <div>
        <Label>Default Git Strategy</Label>
        <p className="text-xs text-neutral-500 mb-1">How the agent manages code changes for new tasks.</p>
        <Select value={settings.defaultGitStrategy} onValueChange={v => updateSettings({ defaultGitStrategy: v as AIGitStrategy })}>
          <SelectTrigger className="w-40">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="branch">Branch</SelectItem>
            <SelectItem value="worktree">Worktree</SelectItem>
            <SelectItem value="none">None</SelectItem>
          </SelectContent>
        </Select>
      </div>
    </div>
  )
}
