import { BrowserWindow } from 'electron'
import { ipcMainHandle } from '../utils/ipc-handle.js'
import { dockerManager } from '../docker/docker-manager.js'

export function registerDockerHandlers(mainWindow: BrowserWindow): void {
  dockerManager.setMainWindow(mainWindow)
  dockerManager.startPolling()

  ipcMainHandle('dockerGetContexts', () => dockerManager.getContexts())
  ipcMainHandle('dockerSwitchContext', (_event, name: string) => dockerManager.switchContext(name))
  ipcMainHandle('dockerGetActiveContext', () => dockerManager.getActiveContext())
  ipcMainHandle('dockerIsAvailable', () => dockerManager.isAvailable())
  ipcMainHandle('dockerGetContainers', (_event, filters?: DockerContainerFilters) => dockerManager.getContainers(filters))
  ipcMainHandle('dockerGetContainer', (_event, id: string, dockerContext?: string) => dockerManager.getContainer(id, dockerContext))
  ipcMainHandle('dockerStartContainer', (_event, id: string, dockerContext?: string) => dockerManager.startContainer(id, dockerContext))
  ipcMainHandle('dockerStopContainer', (_event, id: string, dockerContext?: string) => dockerManager.stopContainer(id, dockerContext))
  ipcMainHandle('dockerRestartContainer', (_event, id: string, dockerContext?: string) => dockerManager.restartContainer(id, dockerContext))
  ipcMainHandle('dockerPauseContainer', (_event, id: string, dockerContext?: string) => dockerManager.pauseContainer(id, dockerContext))
  ipcMainHandle('dockerUnpauseContainer', (_event, id: string, dockerContext?: string) => dockerManager.unpauseContainer(id, dockerContext))
  ipcMainHandle('dockerRemoveContainer', (_event, id: string, force: boolean, dockerContext?: string) => dockerManager.removeContainer(id, force, dockerContext))
  ipcMainHandle('dockerExecInContainer', (_event, id: string, command: string[], dockerContext?: string) => dockerManager.execInContainer(id, command, dockerContext))
  // Interactive Exec
  ipcMainHandle('dockerExecInteractive', (_event, containerId: string, shell: string, dockerContext?: string) => dockerManager.startInteractiveExec(containerId, shell, dockerContext))
  ipcMainHandle('dockerExecInput', (_event, sessionId: string, data: string) => dockerManager.writeToExecSession(sessionId, data))
  ipcMainHandle('dockerExecResize', (_event, sessionId: string, cols: number, rows: number) => dockerManager.resizeExecSession(sessionId, cols, rows))
  ipcMainHandle('dockerExecClose', (_event, sessionId: string) => dockerManager.closeExecSession(sessionId))
  // File Manager
  ipcMainHandle('dockerListDirectory', (_event, containerId: string, path: string, dockerContext?: string) => dockerManager.listDirectory(containerId, path, dockerContext))
  ipcMainHandle('dockerReadFile', (_event, containerId: string, path: string, maxSize?: number, dockerContext?: string) => dockerManager.readFile(containerId, path, maxSize, dockerContext))
  ipcMainHandle('dockerDownloadFile', (_event, containerId: string, remotePath: string, isDirectory?: boolean, dockerContext?: string) => dockerManager.downloadFile(containerId, remotePath, isDirectory, dockerContext))
  ipcMainHandle('dockerUploadFile', (_event, containerId: string, localPath: string, remotePath: string, dockerContext?: string) => dockerManager.uploadFile(containerId, localPath, remotePath, dockerContext))
  ipcMainHandle('dockerUploadFiles', (_event, containerId: string, localPaths: string[], remotePath: string, dockerContext?: string) => dockerManager.uploadFiles(containerId, localPaths, remotePath, dockerContext))
  ipcMainHandle('dockerUploadFileDialog', (_event, containerId: string, remotePath: string, dockerContext?: string) => dockerManager.uploadFileDialog(containerId, remotePath, dockerContext))
  ipcMainHandle('dockerCreateDirectory', (_event, containerId: string, path: string, dockerContext?: string) => dockerManager.createDirectory(containerId, path, dockerContext))
  ipcMainHandle('dockerDeletePath', (_event, containerId: string, path: string, recursive?: boolean, dockerContext?: string) => dockerManager.deletePath(containerId, path, recursive, dockerContext))
  ipcMainHandle('dockerRenamePath', (_event, containerId: string, oldPath: string, newPath: string, dockerContext?: string) => dockerManager.renamePath(containerId, oldPath, newPath, dockerContext))
  ipcMainHandle('dockerStartDrag', (_event, containerId: string, remotePath: string, dockerContext?: string) => dockerManager.startDrag(containerId, remotePath, dockerContext))
  ipcMainHandle('dockerInspectContainer', (_event, id: string, dockerContext?: string) => dockerManager.inspectContainer(id, dockerContext))
  ipcMainHandle('dockerGetContainerLogs', (_event, id: string, options: DockerLogOptions, dockerContext?: string) => dockerManager.getContainerLogs(id, options, dockerContext))
  ipcMainHandle('dockerStreamContainerLogs', (_event, id: string, options: DockerLogOptions, dockerContext?: string) => dockerManager.streamContainerLogs(id, options, dockerContext))
  ipcMainHandle('dockerStopLogStream', (_event, id: string) => dockerManager.stopLogStream(id))
  ipcMainHandle('dockerGetContainerStats', (_event, id: string, dockerContext?: string) => dockerManager.getContainerStats(id, dockerContext))
  ipcMainHandle('dockerGetAllStats', () => dockerManager.getAllStats())
  ipcMainHandle('dockerGetImages', () => dockerManager.getImages())
  ipcMainHandle('dockerPullImage', (_event, name: string) => dockerManager.pullImage(name))
  ipcMainHandle('dockerRemoveImage', (_event, id: string, force: boolean, dockerContext?: string) => dockerManager.removeImage(id, force, dockerContext))
  ipcMainHandle('dockerInspectImage', (_event, id: string) => dockerManager.inspectImage(id))
  ipcMainHandle('dockerGetImageHistory', (_event, id: string) => dockerManager.getImageHistory(id))
  ipcMainHandle('dockerPruneImages', (_event, danglingOnly: boolean) => dockerManager.pruneImages(danglingOnly))
  ipcMainHandle('dockerGetVolumes', () => dockerManager.getVolumes())
  ipcMainHandle('dockerCreateVolume', (_event, name: string, labels?: Record<string, string>) => dockerManager.createVolume(name, labels))
  ipcMainHandle('dockerRemoveVolume', (_event, name: string, dockerContext?: string) => dockerManager.removeVolume(name, dockerContext))
  ipcMainHandle('dockerPruneVolumes', () => dockerManager.pruneVolumes())
  ipcMainHandle('dockerGetNetworks', () => dockerManager.getNetworks())
  ipcMainHandle('dockerCreateNetwork', (_event, name: string, driver: string) => dockerManager.createNetwork(name, driver))
  ipcMainHandle('dockerRemoveNetwork', (_event, id: string, dockerContext?: string) => dockerManager.removeNetwork(id, dockerContext))
  ipcMainHandle('dockerInspectNetwork', (_event, id: string) => dockerManager.inspectNetwork(id))
  ipcMainHandle('dockerGetComposeProjects', () => dockerManager.getComposeProjects())
  ipcMainHandle('dockerComposeUp', (_event, project: string) => dockerManager.composeUp(project))
  ipcMainHandle('dockerComposeDown', (_event, project: string) => dockerManager.composeDown(project))
  ipcMainHandle('dockerComposeRestart', (_event, project: string) => dockerManager.composeRestart(project))
  ipcMainHandle('dockerGetDashboardStats', () => dockerManager.getDashboardStats())
  ipcMainHandle('dockerGetSystemInfo', () => dockerManager.getSystemInfo())
  ipcMainHandle('dockerSystemPrune', (_event, includeVolumes: boolean) => dockerManager.systemPrune(includeVolumes))
}
